### ISSUE TITLE
Can not scan by "sudo hcitool lescan" !

### ISSUE THREAD

**Issue by tinamore** [lijunxyz/nRF24_BLE#1]
Hi
Thank for great project.
I have a problem: I see nRF24 device in list device app android "nRF Master Control Panel”.  It scan every good.

But when i scan in linux: **sudo hcitool lescan** . Document: https://learn.adafruit.com/reverse-engineering-a-bluetooth-low-energy-light-bulb/control-with-bluez
==> Can not see "nRF24".

Can you help me!

**Comment by lijuno** [comment]
@tinamore It was also a little hard for me to see this nRF24 beacon in Linux with a BLE HCI adapter. I shortened the BLE advertizing interval, and change the flag to "general discoverable" in [my code here](https://github.com/lijunhw/nRF24_BLE/blob/master/Arduino/nRF24_BLE_advertizer_demo/nRF24_BLE_advertizer_demo.ino). If you do: 

```
sudo hcitool lescan | grep "66:55:44:33:22:11"
```

You may be able to see some "nRF24" scanning record. However, I needed to wait for a while to see the "nRF24" beacon. Still not sure if it was related to the timing jittering or something else.
