### ISSUE TITLE
Byte order reversal

### ISSUE THREAD

**Issue by saintnever** [lijunxyz/nRF24_BLE#2]
Hi Lijun,

I am trying to port your code to MSP430 SPI to clock out Bluetooth packets. As you pointed out, both the byte order and bit order inside each byte are reversed for Bluetooth packets. However, I do not see any byte reversal in your code, only bit reversal for single bytes. Could you explain why? Is it has something to do with nRF24L01+?

thanks
TX

**Comment by lijuno** [comment]
If you meant [this part](https://github.com/lijuno/nRF24_BLE/blob/0356206edb41424c0d176535c2b3c158b8e54139/Arduino/nRF24_BLE_advertizer_demo/nRF24_BLE_advertizer_demo.ino#L149-L152), the bytes from `buf[1]` to `buf[4]` were reversed from `0x8E89BED6`.
